name: ShopingKaro CI/CD

on:
  push:
    branches:
      - master

jobs:
  ci-cd:
    runs-on: [self-hosted]

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Environment (Node.js, npm, PM2, Docker)
      - name: Setup Environment
        run: |
          echo "Checking Node.js..."
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi
          echo "Node.js version: $(node -v)"

          echo "Checking npm..."
          if ! command -v npm &> /dev/null; then
            sudo apt install -y npm
          fi
          echo "npm version: $(npm -v)"

          echo "Checking PM2..."
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi
          echo "PM2 version: $(pm2 -v)"

          echo "Checking Docker..."
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed. Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
          fi
          echo "Docker version: $(docker --version)"

      # 3️⃣ Start MongoDB in Docker safely
      - name: Start MongoDB Docker
        run: |
          echo "Removing existing MongoDB container if exists..."
          if [ "$(docker ps -aq -f name=shoppingkaro-mongo)" ]; then
            docker rm -f shoppingkaro-mongo
          fi

          echo "Starting new MongoDB container..."
          docker run -d --name shoppingkaro-mongo -p 27017:27017 mongo:6.0

      # 4️⃣ Clean old artifacts and install dependencies
      - name: Clean & Install Dependencies
        run: |
          echo "Stopping old application..."
          pm2 stop ShopingKaro || true
          pm2 delete ShopingKaro || true

          echo "Cleaning old node_modules and build..."
          rm -rf node_modules
          rm -rf dist || true

          echo "Installing dependencies..."
          npm install

          echo "Building application..."
          npm run build || echo "No build script defined, skipping"

      # 5️⃣ Deploy application with PM2 on port 8087
      - name: Deploy Application
        run: |
          APP_NAME="ShopingKaro"
          PORT=8087
          export PORT=$PORT

          echo "Starting application..."
          pm2 start npm --name $APP_NAME -- start
          pm2 save

      # 6️⃣ Run tests
      - name: Run Tests
        run: npm test
