name: CI/CD ShopingKaro

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Docker & Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Clean old containers and PM2 processes
        run: |
          docker rm -f shoppingkaro-mongo || true
          pm2 stop all || true
          pm2 delete all || true

      - name: Start MongoDB Docker container
        run: |
          docker run -d --name shoppingkaro-mongo -p 27017:27017 mongo:6.0

      - name: Create .env file
        run: |
          echo "MONGO_DB_URI=mongodb://localhost:27017/shoppingkaro" > .env
          echo "PORT=8087" >> .env

      - name: Install dependencies
        run: |
          npm install

      - name: Build app (if build script exists)
        run: |
          if npm run build; then echo "Build done"; else echo "No build script"; fi

      - name: Run tests (if test script exists)
        run: |
          if npm test; then echo "Tests passed"; else echo "No tests or failed"; fi

      - name: Start app via PM2
        run: |
          export PORT=8087
          pm2 start index.js --name ShopingKaro --watch
          pm2 save

      - name: Verify app status
        run: |
          pm2 status
          sudo lsof -i -P -n | grep LISTEN | grep 8087
          curl -f http://localhost:8087 || echo "App not reachable yet"
