name: ShopingKaro Self-Hosted CI

# Trigger on push to main branch
on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests (optional)
      - name: Run tests
        run: npm test || echo "No tests found or failed"

      # 5. Start the app on port 8087
      - name: Start ShopingKaro App
        run: |
          export PORT=8087
          nohup npm run start > app.log 2>&1 &
          echo "ShopingKaro started on port 8087"
